version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mean_app_backend
    ports:
      - "3001:3000" # Host port 3001 -> Container port 3000
    environment:
      - DB_URL=mongodb://mongo:27017/crud-dd-task
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mean_app_frontend
    ports:
      - "8081:80" # Host port 8081 -> Container port 80
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mean_app_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
